### ISSUE TITLE
alpm_sync_newversion replaced with alpm_sync_get_new_version

### ISSUE THREAD

**Issue by EndlessEden** [archlinuxfr/package-query#143]
upstream, libalpm was changed recently to replace alpm_sync_newversion with alpm_sync_get_new_version. Changing the functionality of it as well.

see commit: [e9d91a688d1a2ebe58e8a895853debf745a529cf](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pacman&id=c09cc29fa2b5d4b6a3a429112ada4f0e857dbafa)

**Comment by vanbreukelingen** [comment]
build your own: worked for me:
https://ftp.sjtu.edu.cn/sites/ftp.archlinux.org/other/pacman/

**Comment by fabmazz** [comment]
trying to build "package-query-git" from AUR, the following error occurs:
```/usr/bin/ld: alpm-query.o: in function `filter':
alpm-query.c:(.text+0x895): undefined reference to `alpm_sync_newversion'
```
I guess this is due to the library change

**Comment by f2404** [comment]
Fixed by https://github.com/archlinuxfr/package-query/commit/ab3f6a151d1dac8788cacbfbd708e7f2600fdf5b

**Comment by vanbreukelingen** [comment]
not fixed -same output - and with the built I can't use AUR.

**Comment by f2404** [comment]
The "package-query-git" AUR package works for me.
I will update the "package-query" package later today.

**Comment by f2404** [comment]
The "package-query" AUR package has been updated for release 1.10.
